# Generated by Django 4.2.7 on 2023-11-13 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=20, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('staff_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('platform_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_of_payment', models.CharField(max_length=20)),
                ('razorpay_paid', models.BooleanField(default=False, null=True)),
                ('razorpay_order_id', models.CharField(max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=100, null=True)),
                ('razorpay_payment_signature', models.CharField(max_length=100, null=True)),
                ('appointment_completion', models.BooleanField(default=False)),
            ],
        ),
    ]
