# Generated by Django 4.2.7 on 2023-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveprofile',
            name='document',
        ),
        migrations.AddField(
            model_name='executiveprofile',
            name='document_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
