# Generated by Django 4.2.7 on 2023-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointments_lab_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='report',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
