# Generated by Django 4.2.7 on 2023-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_and_labs', '0004_remove_labavailability_slots_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='labprofile',
            name='document',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='document_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labprofile',
            name='document_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
